"use strict";

/** @type {{ Name: TitleName; Requirement: () => boolean; Earned?: boolean, Force?: boolean }[]} */
var TitleList = [
	{ Name: "None", Requirement: function () { return true; } },
	{ Name: "Mistress", Requirement: function () { return LogQuery("ClubMistress", "Management") && !Player.GenderSettings.HideTitles.Female; }, Earned: true },
	{ Name: "Master", Requirement: function () { return LogQuery("ClubMistress", "Management") && !Player.GenderSettings.HideTitles.Male; }, Earned: true },
	{ Name: "Queen", Requirement: function () { return (ReputationGet("Dominant") >= 75) && !Player.GenderSettings.HideTitles.Female; }, Earned: true },
	{ Name: "King", Requirement: function () { return (ReputationGet("Dominant") >= 75) && !Player.GenderSettings.HideTitles.Male; }, Earned: true },
	{ Name: "Goddess", Requirement: function () { return (ReputationGet("Dominant") >= 100) && !Player.GenderSettings.HideTitles.Female; }, Earned: true },
	{ Name: "God", Requirement: function () { return (ReputationGet("Dominant") >= 100) && !Player.GenderSettings.HideTitles.Male; }, Earned: true },
	{ Name: "Mistree", Requirement: function () { return LogQuery("ClubMistress", "Management"); }, Earned: true },
	{ Name: "ClubSlave", Requirement: function () { return ManagementIsClubSlave(); }, Force: true },
	{ Name: "FreeUse", Requirement: function () { return (ReputationGet("Dominant") <= -100); }, Earned: true },
	{ Name: "Archjudge", Requirement: function () { return (ReputationGet("Dominant") >= 90); }, Earned: true },
	{ Name: "Judge", Requirement: function () { return (ReputationGet("Dominant") >= 50); }, Earned: true },
	{ Name: "Archbishop", Requirement: function () { return ((ReputationGet("HouseVincula") >= 75) || (ReputationGet("HouseMaiestas") >= 75) || (ReputationGet("HouseCorporis") >= 75) || (ReputationGet("HouseAmplector") >= 75)); }, Earned: true },
	{ Name: "Bishop", Requirement: function () { return ((ReputationGet("HouseVincula") >= 25) || (ReputationGet("HouseMaiestas") >= 25) || (ReputationGet("HouseCorporis") >= 25) || (ReputationGet("HouseAmplector") >= 25)); }, Earned: true },
	{ Name: "Champion", Requirement: function () { return (ReputationGet("LARP") >= 100); }, Earned: true },
	{ Name: "Matron", Requirement: function () { return (ReputationGet("Maid") >= 50) && (ReputationGet("Dominant") >= 50) && !Player.GenderSettings.HideTitles.Female; }, Earned: true },
	{ Name: "Patriarch", Requirement: function () { return (ReputationGet("Maid") >= 50) && (ReputationGet("Dominant") >= 50) && !Player.GenderSettings.HideTitles.Female; }, Earned: true },
	{ Name: "Primaris", Requirement: function () { return (ReputationGet("Asylum") >= 50) && (ReputationGet("Dominant") >= 50); }, Earned: true },
	{ Name: "Maid", Requirement: function () { return (LogQuery("JoinedSorority", "Maid") && !LogQuery("LeadSorority", "Maid")); }, Earned: true },
	{ Name: "HeadMaid", Requirement: function () { return LogQuery("LeadSorority", "Maid"); }, Earned: true },
	{ Name: "BondageMaid", Requirement: function () { return ((LogQuery("JoinedSorority", "Maid") || LogQuery("LeadSorority", "Maid")) && SkillGetLevel(Player, "Evasion") >= 10); }, Earned: true },
	{ Name: "Kidnapper", Requirement: function () { return ((ReputationGet("Kidnap") >= 50) && (ReputationGet("Kidnap") < 100)); }, Earned: true },
	{ Name: "MasterKidnapper", Requirement: function () { return (ReputationGet("Kidnap") >= 100); }, Earned: true },
	{ Name: "Patient", Requirement: function () { return ((ReputationGet("Asylum") <= -50) && (ReputationGet("Asylum") > -100)); }, Earned: true },
	{ Name: "PermanentPatient", Requirement: function () { return (ReputationGet("Asylum") <= -100); }, Earned: true },
	{ Name: "EscapedPatient", Requirement: function () { return ((LogValue("Escaped", "Asylum") ?? 0) >= CurrentTime); }, Force: true },
	{ Name: "Nurse", Requirement: function () { return ((ReputationGet("Asylum") >= 50) && (ReputationGet("Asylum") < 100)); }, Earned: true },
	{ Name: "Doctor", Requirement: function () { return (ReputationGet("Asylum") >= 100); }, Earned: true },
	{ Name: "AnimeGirl", Requirement: function () { return InventoryAvailable(Player, "AnimeGirl", "Cloth") && !Player.GenderSettings.HideTitles.Female; }, Earned: true },
	{ Name: "AnimeBoy", Requirement: function () { return InventoryAvailable(Player, "AnimeGirl", "Cloth") && !Player.GenderSettings.HideTitles.Male; }, Earned: true },
	{ Name: "LadyLuck", Requirement: function () { return (ReputationGet("Gambling") >= 100) && !Player.GenderSettings.HideTitles.Female; }, Earned: true },
	{ Name: "LordFortune", Requirement: function () { return (ReputationGet("Gambling") >= 100) && !Player.GenderSettings.HideTitles.Male; }, Earned: true },
	{ Name: "Patron", Requirement: function () { return CheatAllow; }, Earned: true },
	{ Name: "CollegeStudent", Requirement: function () { return LogQuery("BondageCollege", "Import"); }, Earned: true },
	{ Name: "Nawashi", Requirement: function () { return (SkillGetLevel(Player, "Bondage") >= 10); }, Earned: true },
	{ Name: "Houdini", Requirement: function () { return (SkillGetLevel(Player, "Evasion") >= 10); }, Earned: true },
	{ Name: "PonyAlicorn", Requirement: function () { return (SkillGetLevel(Player, "Dressage") >= 10); }, Earned: true },
	{ Name: "PonyPegasus", Requirement: function () { return ((SkillGetLevel(Player, "Dressage") >= 8) && (SkillGetLevel(Player, "Dressage") <= 9)); }, Earned: true },
	{ Name: "PonyUnicorn", Requirement: function () { return (SkillGetLevel(Player, "Dressage") == 7); }, Earned: true },
	{ Name: "PonyWild", Requirement: function () { return (SkillGetLevel(Player, "Dressage") == 6); }, Earned: true },
	{ Name: "PonyHot", Requirement: function () { return (SkillGetLevel(Player, "Dressage") == 5); }, Earned: true },
	{ Name: "PonyWarm", Requirement: function () { return (SkillGetLevel(Player, "Dressage") == 4); }, Earned: true },
	{ Name: "PonyCold", Requirement: function () { return (SkillGetLevel(Player, "Dressage") == 3); }, Earned: true },
	{ Name: "PonyFarm", Requirement: function () { return (SkillGetLevel(Player, "Dressage") == 2); }, Earned: true },
	{ Name: "PonyFoal", Requirement: function () { return ((SkillGetLevel(Player, "Dressage") == 1) || ((SkillGetLevel(Player, "Dressage") >= 1) && (ReputationGet("ABDL") >= 1))); }, Earned: true },
	{ Name: "InfilrationMole", Requirement: function () { return ((SkillGetLevel(Player, "Infiltration") == 2) || (SkillGetLevel(Player, "Infiltration") == 3)); }, Earned: true },
	{ Name: "InfilrationInfiltrator", Requirement: function () { return ((SkillGetLevel(Player, "Infiltration") == 4) || (SkillGetLevel(Player, "Infiltration") == 5)); }, Earned: true },
	{ Name: "InfilrationAgent", Requirement: function () { return ((SkillGetLevel(Player, "Infiltration") == 6) || (SkillGetLevel(Player, "Infiltration") == 7)); }, Earned: true },
	{ Name: "InfilrationOperative", Requirement: function () { return ((SkillGetLevel(Player, "Infiltration") == 8) || (SkillGetLevel(Player, "Infiltration") == 9)); }, Earned: true },
	{ Name: "InfilrationSuperspy", Requirement: function () { return (SkillGetLevel(Player, "Infiltration") >= 10); }, Earned: true },
	{ Name: "MagicSchoolWizard", Requirement: function () { return (ReputationGet("HouseMaiestas") >= 50); }, Earned: true },
	{ Name: "MagicSchoolMagus", Requirement: function () { return (ReputationGet("HouseMaiestas") >= 100); }, Earned: true },
	{ Name: "MagicSchoolMagician", Requirement: function () { return (ReputationGet("HouseVincula") >= 50); }, Earned: true },
	{ Name: "MagicSchoolSorcerer", Requirement: function () { return (ReputationGet("HouseVincula") >= 100); }, Earned: true },
	{ Name: "MagicSchoolSage", Requirement: function () { return (ReputationGet("HouseAmplector") >= 50); }, Earned: true },
	{ Name: "MagicSchoolOracle", Requirement: function () { return (ReputationGet("HouseAmplector") >= 100); }, Earned: true },
	{ Name: "MagicSchoolWitch", Requirement: function () { return (ReputationGet("HouseCorporis") >= 50); }, Earned: true },
	{ Name: "MagicSchoolWarlock", Requirement: function () { return (ReputationGet("HouseCorporis") >= 100); }, Earned: true },
	{ Name: "Duchess", Requirement: function () { return LogQuery("KidnapSophie", "Sarah") && !Player.GenderSettings.HideTitles.Female; }, Earned: true },
	{ Name: "Duke", Requirement: function () { return LogQuery("KidnapSophie", "Sarah") && !Player.GenderSettings.HideTitles.Male; }, Earned: true },
	{ Name: "LittleOne", Requirement: function () { return (ReputationGet("ABDL") >= 1); }, Earned: true },
	{ Name: "Baby", Requirement: function () { return (ReputationGet("ABDL") >= 1); }, Earned: true },
	{ Name: "DL", Requirement: function () { return (ReputationGet("ABDL") >= 1); }, Earned: true },
	{ Name: "BondageBaby", Requirement: function () { return ((SkillGetLevel(Player, "Evasion")) >= 10 && (ReputationGet("ABDL") >= 1)); }, Earned: true },
	{ Name: "Switch", Requirement: function () { return true; } },
	{ Name: "Princess", Requirement: function () { return !Player.GenderSettings.HideTitles.Female; } },
	{ Name: "Prince", Requirement: function () { return !Player.GenderSettings.HideTitles.Male; } },
	{ Name: "Liege", Requirement: function () { return true; } },
	{ Name: "Majesty", Requirement: function () { return true; } },
	{ Name: "Missy", Requirement: function () { return !Player.GenderSettings.HideTitles.Female; } },
	{ Name: "Sissy", Requirement: function () { return !Player.GenderSettings.HideTitles.Male; } },
	{ Name: "Tomboy", Requirement: function () { return !Player.GenderSettings.HideTitles.Female; } },
	{ Name: "Femboy", Requirement: function () { return !Player.GenderSettings.HideTitles.Male; } },
	{ Name: "GoodOne", Requirement: function () { return true; } },
	{ Name: "Pet", Requirement: function () { return true; } },
	{ Name: "Dragon", Requirement: function () { return true; } },
	{ Name: "Wolf", Requirement: function () { return true; } },
	{ Name: "Monster", Requirement: function () { return true; } },
	{ Name: "Shapeshifter", Requirement: function () { return true; } },
	{ Name: "Vampire", Requirement: function () { return true; } },
	{ Name: "Brat", Requirement: function () { return true; } },
	{ Name: "Kitten", Requirement: function () { return true; } },
	{ Name: "Puppy", Requirement: function () { return true; } },
	{ Name: "Foxy", Requirement: function () { return true; } },
	{ Name: "Bunny", Requirement: function () { return true; } },
	{ Name: "Turtle", Requirement: function () { return true; } },
	{ Name: "Thing", Requirement: function () { return true; } },
	{ Name: "Doll", Requirement: function () { return true; } },
	{ Name: "Demon", Requirement: function () { return true; } },
	{ Name: "Elf", Requirement: function () { return true; } },
	{ Name: "Drow", Requirement: function () { return true; } },
	{ Name: "Pixie", Requirement: function () { return true; } },
	{ Name: "Angel", Requirement: function () { return true; } },
	{ Name: "Alien", Requirement: function () { return true; } },
	{ Name: "Captain", Requirement: function () { return true; } },
	{ Name: "Admiral", Requirement: function () { return true; } },
	{ Name: "Succubus", Requirement: function () { return !Player.GenderSettings.HideTitles.Female; } },
	{ Name: "Incubus", Requirement: function () { return !Player.GenderSettings.HideTitles.Male; } },
	{ Name: "Concubus", Requirement: function () { return true; } },
	{ Name: "GoodGirl", Requirement: function () { return (AsylumGGTSGetLevel(Player) >= 4) && !Player.GenderSettings.HideTitles.Female; }, Earned: true },
	{ Name: "GoodSlaveGirl", Requirement: function () { return (AsylumGGTSGetLevel(Player) >= 5) && !Player.GenderSettings.HideTitles.Female; }, Earned: true },
	{ Name: "GoodBoy", Requirement: function () { return (AsylumGGTSGetLevel(Player) >= 4) && !Player.GenderSettings.HideTitles.Male; }, Earned: true },
	{ Name: "GoodSlaveBoy", Requirement: function () { return (AsylumGGTSGetLevel(Player) >= 5) && !Player.GenderSettings.HideTitles.Male; }, Earned: true },
	{ Name: "GoodSlave", Requirement: function () { return (AsylumGGTSGetLevel(Player) >= 6); }, Earned: true },
	{ Name: "Drone", Requirement: function () { return (AsylumGGTSGetLevel(Player) >= 6); }, Earned: true }
];
